In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('../data/processed/dollar_price_final.csv', index_col=0, parse_dates=True)
df.index.name = 'Date'
df.head()

,Open,Low,High,Close,DayOfWeek,Is_Imputed,Daily_Return
Date,,,,,,,
2011-11-27,13700.0,13700.0,13700.0,13700.0,Sunday,False,NaN
2011-11-28,13440.0,13440.0,13440.0,13440.0,Monday,False,-0.018978
2011-11-29,13350.0,13350.0,13350.0,13350.0,Tuesday,False,-0.006696
2011-11-30,13400.0,13400.0,13400.0,13400.0,Wednesday,False,0.003745
2011-12-01,13500.0,13500.0,13500.0,13500.0,Thursday,False,0.007463

# ساخت فیچرهای Lag (تاخیری)

In [23]:
df['Close_Lag_1'] = df['Close'].shift(1)
df['Close_Lag_3'] = df['Close'].shift(3)
df['Close_Lag_7'] = df['Close'].shift(7)

In [24]:
df[['Close', 'Close_Lag_1', 'Close_Lag_3', 'Close_Lag_7']].head(10)

              Close  Close_Lag_1  Close_Lag_3  Close_Lag_7
Date
2011-11-27  13700.0          NaN          NaN          NaN
2011-11-28  13440.0      13700.0          NaN          NaN
2011-11-29  13350.0      13440.0          NaN          NaN
2011-11-30  13400.0      13350.0      13700.0          NaN
2011-12-01  13500.0      13400.0      13440.0          NaN
2011-12-02  13500.0      13500.0      13350.0          NaN
2011-12-03  13650.0      13500.0      13400.0          NaN
2011-12-04  13610.0      13650.0      13500.0      13700.0
2011-12-05  13610.0      13610.0      13500.0      13440.0
2011-12-06  13610.0      13610.0      13650.0      13350.0

# Moving Average

In [25]:
df['MA_7'] = df['Close'].rolling(window=7).mean()
df['MA_30'] = df['Close'].rolling(window=30).mean()

In [26]:
df[['Close', 'MA_7', 'MA_30']].tail(10)

               Close           MA_7          MA_30
Date
2023-06-26  497810.0  496457.142857  498180.333333
2023-06-27  492820.0  496947.142857  497437.000000
2023-06-28  492230.0  497875.714286  496605.666667
2023-06-29  492230.0  497175.714286  495929.333333
2023-06-30  492230.0  496475.714286  495392.333333
2023-07-01  498220.0  494991.428571  494970.000000
2023-07-02  499340.0  494982.857143  494585.000000
2023-07-03  502000.0  495581.428571  494310.666667
2023-07-04  500750.0  496714.285714  493994.666667
2023-07-05  500950.0  497960.000000  493685.333333

حذف ردیف‌های ناقص (به‌خاطر NaN های ابتدای داده)

In [27]:
df = df.dropna()

In [28]:
df.isnull().sum()

Open            0
Low             0
High            0
Close           0
DayOfWeek       0
Is_Imputed      0
Daily_Return    0
Close_Lag_1     0
Close_Lag_3     0
Close_Lag_7     0
MA_7            0
MA_30           0
dtype: int64

In [29]:
df.shape

(4036, 12)

In [30]:
df['MA_7'] = df['Close'].rolling(window=7).mean()

In [31]:
test = pd.Series([10,20,30,40,50,60,70])
print(test.rolling(window=3).mean())

0     NaN
1     NaN
2    20.0
3    30.0
4    40.0
5    50.0
6    60.0
dtype: float64

میانگین متحرک رو یک روز عقب بکشیم

In [32]:
df['MA_7'] = df['Close'].shift(1).rolling(window=7).mean()
df['MA_30'] = df['Close'].shift(1).rolling(window=30).mean()

In [33]:
test = pd.Series([10, 20, 30, 40, 50, 60, 70])
print(test.shift(1).rolling(window=3).mean())

0     NaN
1     NaN
2     NaN
3    20.0
4    30.0
5    40.0
6    50.0
dtype: float64

حذف دوباره NaN

In [34]:
df = df.dropna()
df.shape

(4006, 12)

In [35]:
df.to_csv('../data/processed/dollar_price_features.csv')